### ISSUE TITLE
This is Amazing!!!!!!!

### ISSUE THREAD

**Issue by mac7988** [filoucool/Python-Pick-and-Place#8]
I was looking for someone to develop this for a long time. I wanted to use a 4 axis cartesion robot to pick and place from a known 0x 0y position. I just want to send a command "pick" and the program will send a x and y position to a csv. I will transform this to a gcode for pick up and drop off.

**Comment by filoucool** [comment]
The pick and place script is not fully done. Maybe the current version is going to work for you, who knows
